language: cpp
dist: xenial
compiler:
    - g++
before_install:
    - sudo apt update
    - sudo apt install cmake
script:
    - ./install_dependencies.sh
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
    - make package
    - sudo dpkg -i *.deb
