language: cpp
matrix:
    include:
        - name: 'xenial g++'
          dist: xenial
          compiler: g++
        - name: 'xenial clang++'
          dist: xenial
          compiler: clang++
cache: ccache
before_install:
    - sudo apt update
    - sudo apt install wget make ccache
    - wget https://cmake.org/files/v3.11/cmake-3.11.1-Linux-x86_64.sh
    - sudo sh cmake-3.11.1-Linux-x86_64.sh --prefix=/usr/local --skip-license --exclude-directory
script:
    - export PATH=/usr/local/bin:$PATH
    - ./install_dependencies.sh --enable-tests
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
    - make package
    - sudo dpkg -i *.deb
    - cd ..
    - snapcraft
deploy:
    provider: snap
    snap: timetabler_*.snap
    channel: edge
    skip_cleanup: true
