instructors:
  - A

classrooms:
  - number: 1
    size: 50
  - number: 2
    size: 30
  

segments:
  start: 1
  end: 6

slots:
  - name: "B"
    is_minor: false
    time_periods:
      - day: "Tuesday"
        start: "10:00"
        end: "11:00"

programs:
  - "B.Tech.1"
  - "B.Tech.2"
