instructors:
  - A
  - B

classrooms:
  - number: 1
    size: 50
  - number: 2
    size: 50

segments:
  start: 1
  end: 2

slots:
  - name: A
    is_minor: false
    time_periods:
      - day: "Tuesday"
        start: "10:00"
        end: "11:00"
  - name: B
    is_minor: false
    time_periods:
      - day: "Tuesday"
        start: "10:00"
        end: "13:00"

programs:
  - "B.Tech.1"