courses:
  - name: "CS6403"
    class_size: 50
    instructor: "Dr. Saurabh Joshi"
    programs:
      - name: "B.Tech.1"
        course_type: "Core"
      - name: "B.Tech.2"
        course_type: "Elective"
    segment: "14"
    is_minor: false
  - name: "CS6383"
    class_size: 30
    instructor: "Dr. Ramakrishna Upadrasta"
    programs:
      - name: "B.Tech.3"
        course_type: "Elective"
      - name: "M.Tech."
        course_type: "Core"
    segment: "16"
    is_minor: true
