weights: # Assignment, high level
  instructor: [1, 1]
  segment: [1, 1]
  is_minor: [1, 1]
  program: 1
  classroom: [1, 1]
  slot: [1, 1]

# Predefined Weights
# instructorSingleCourseAtATime
# classroomSingleCourseAtATime
# programSingleCoreCourseAtATime
# minorInMinorTime
# exactlyOneSlotPerCourse
# exactlyOneInstructorPerCourse
# exactlyOneSegmentPerCourse
# exactlyOneIsMinorPerCourse
# exactlyOneClassroomPerCourse
# coreInMorningTime
# programAtMostOneOfCoreOrElective

predefined_weights:
  - clause: 0
    weight: 1

segments:
  start: 1
  end: 6

instructors:
  - Antony Franklin
  - NR Aravind
  - Bheemarjuna Reddy Tamma
  - C Krishna Mohan
  - Kotaro Kataoka
  - Maunendra S Desarkar
  - Manohar Kaul
  - Manish Singh
  - MVP Rao
  - Ramakrishna Upadrasta
  - Saketha Nath
  - Sathya Peri
  - Saurabh Joshi
  - Sobhan Babu
  - Sparsh Mittal
  - Srijith PK
  - Subrahmanyam Kalyanasundaram
  - Vineeth NB

classrooms:
  - number: 212
    size: 20
  - number: 119
    size: 50
  - number: 317
    size: 50
  - number: Auditorium
    size: 200

programs:
  - CS14B
  - CS15B
  - CS16B
  - CS17B
  - CS15M
  - CS16M
  - CS17M
  - PHD

slots:
  - name: A
    is_minor: false
    time_periods:
      - day: Monday
        start: 9:00
        end: 9:55
      - day: Wednesday
        start: 11:00
        end: 11:55
      - day: Thursday
        start: 10:00
        end: 10:55
  - name: B
    is_minor: false
    time_periods:
      - day: Monday
        start: 10:00
        end: 10:55
      - day: Wednesday
        start: 9:00
        end: 9:55
      - day: Thursday
        start: 11:00
        end: 11:55
  - name: C
    is_minor: false
    time_periods:
      - day: Monday
        start: 11:00
        end: 11:55
      - day: Wednesday
        start: 10:00
        end: 10:55
      - day: Thursday
        start: 9:00
        end: 9:55
  - name: D
    is_minor: false
    time_periods:
      - day: Monday
        start: 12:00
        end: 12:55
      - day: Tuesday
        start: 9:00
        end: 9:55
      - day: Friday
        start: 11:00
        end: 11:55
  - name: E
    is_minor: false
    time_periods:
      - day: Tuesday
        start: 10:00
        end: 10:55
      - day: Thursday
        start: 12:00
        end: 12:55
      - day: Friday
        start: 9:00
        end: 9:55
  - name: F
    is_minor: false
    time_periods:
      - day: Tuesday
        start: 11:00
        end: 11:55
      - day: Wednesday
        start: 14:30
        end: 15:25
      - day: Friday
        start: 10:00
        end: 10:55
  - name: G
    is_minor: false
    time_periods:
      - day: Tuesday
        start: 12:00
        end: 12:55
      - day: Wednesday
        start: 12:00
        end: 12:55
      - day: Friday
        start: 12:00
        end: 12:55
  - name: FN1
    is_minor: false
    time_periods:
      - day: Monday
        start: 9:00
        end: 11:55
  - name: FN2
    is_minor: false
    time_periods:
      - day: Tuesday
        start: 9:00
        end: 11:55
  - name: FN3
    is_minor: false
    time_periods:
      - day: Wednesday
        start: 9:00
        end: 11:55
  - name: FN4
    is_minor: false
    time_periods:
      - day: Thursday
        start: 9:00
        end: 11:55
  - name: FN5
    is_minor: false
    time_periods:
      - day: Friday
        start: 9:00
        end: 11:55
  - name: P
    is_minor: false
    time_periods:
      - day: Monday
        start: 14:30
        end: 15:55
      - day: Thursday
        start: 16:00
        end: 17:25
  - name: Q
    is_minor: false
    time_periods:
      - day: Monday
        start: 16:00
        end: 17:25
      - day: Thursday
        start: 14:30
        end: 15:55
  - name: R
    is_minor: false
    time_periods:
      - day: Tuesday
        start: 14:30
        end: 15:55
      - day: Friday
        start: 16:00
        end: 17:25
  - name: S
    is_minor: false
    time_periods:
      - day: Tuesday
        start: 16:00
        end: 17:25
      - day: Friday
        start: 14:30
        end: 15:55
  - name: W
    is_minor: false
    time_periods:
      - day: Monday
        start: 17:30
        end: 18:55
      - day: Thursday
        start: 17:00
        end: 18:55
  - name: X
    is_minor: false
    time_periods:
      - day: Monday
        start: 19:00
        end: 20:25
      - day: Thursday
        start: 19:00
        end: 20:25
  - name: Y
    is_minor: false
    time_periods:
      - day: Tuesday
        start: 17:30
        end: 18:55
      - day: Friday
        start: 17:00
        end: 18:55
  - name: Z
    is_minor: false
    time_periods:
      - day: Tuesday
        start: 19:00
        end: 20:25
      - day: Friday
        start: 19:00
        end: 20:25
  - name: AN1
    is_minor: false
    time_periods:
      - day: Monday
        start: 14:30
        end: 17:25
  - name: AN2
    is_minor: false
    time_periods:
      - day: Tuesday
        start: 14:30
        end: 17:25
  - name: AN3
    is_minor: false
    time_periods:
      - day: Wednesday
        start: 14:30
        end: 17:25
  - name: AN4
    is_minor: false
    time_periods:
      - day: Thursday
        start: 14:30
        end: 17:25
  - name: AN5
    is_minor: false
    time_periods:
      - day: Friday
        start: 14:30
        end: 17:25