name: timetabler
version: git
version-script:
  ./gen_version.sh . 1
summary: Timetable scheduling software using MaxSAT solver.
description: |
  A highly customizable timetabling software for educational institutions
  that encodes timetabling constraints as a SAT formula and solves them
  using a MaxSAT solver.
type: app
grade: stable
confinement: strict

apps:
  timetabler:
    command: timetabler
    plugs: [home]

parts:
  timetabler:
    plugin: cmake
    override-build: |
      cd ../src/
      bash install_dependencies.sh --parallel
      cd -
      snapcraftctl build
    configflags:
      - -DOPEN_WBO_PATH=../src/dependencies/open-wbo
      - -DYAML_CPP_PATH=../src/dependencies/yaml-cpp
      - -DCSVPARSER_PATH=../src/dependencies/CSVparser
      - -DPEGTL_PATH=../src/dependencies/PEGTL
