name: timetabler
version: "0.3.0-dev"
summary: Timetabler
description: |
  A highly customizable timetabling software for educational institutions
  that encodes timetabling constraints as a SAT formula and solves them
  using a MaxSAT solver.

grade: devel
confinement: devmode

apps:
  timetabler:
    command: timetabler

parts:
  timetabler:
    plugin: cmake
