name: timetabler
version: git
version-script:
  ./gen_version.sh . 1
summary: Timetable scheduling software using MaxSAT solver.
description: |
  A highly customizable timetabling software for educational institutions
  that encodes timetabling constraints as a SAT formula and solves them
  using a MaxSAT solver.
type: app
grade: stable
confinement: strict

apps:
  timetabler:
    command: timetabler
    plugs: [home]

parts:
  timetabler:
    plugin: cmake
    override-build: |
      bash ../src/install_dependencies.sh --parallel
      snapcraftctl build
    configflags:
      - -DOPEN_WBO_PATH=dependencies/open-wbo
      - -DYAML_CPP_PATH=dependencies/yaml-cpp
      - -DCSVPARSER_PATH=dependencies/CSVparser
      - -DPEGTL_PATH=dependencies/PEGTL
